name: Add labels to pull request based on checklist

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check if checklist items are completed
        uses: mheap/require-checklist-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          requireChecklist: true
