name: Add labels to pull request based on checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check if checklist items are completed
        run: |
          completed=$(jq -r '.body' < $GITHUB_EVENT_PATH | grep -E '^\s*- \[x\].*')
          if echo "$completed" | grep -qE '^\s*- \[ \].*'; then
            echo "Checklist items not completed"
            echo "::set-output name=labels::Checklist Items Incomplete"
          else
            echo "Checklist items completed"
            echo "::set-output name=labels::Checklist Items Complete"
          fi

      - name: Add labels
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
            
            const currentLabels = pullRequest.labels.map(label => label.name)
            const newLabels = JSON.parse(process.env.labels)
            
            for (const label of newLabels) {
              if (!currentLabels.includes(label)) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  labels: [label]
                })
              }
            }
            
            for (const label of currentLabels) {
              if (!newLabels.includes(label)) {
                await github.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  name: label
                })
              }
            })
