name: Add labels to pull request based on checklist

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    permissions: read-all|write-all

    steps:
      - name: Check if checklist items are completed
        uses: preda-bogdan/gha-pr-check-helper@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          requireChecklist: true
          onlyCheckBody: true
          completedLabel: "test-checklist-completed"
          incompleteLabel: "test-checklist-incomplete"
