name: Add labels to pull request based on checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check if checklist items are completed
        run: |
          completed=$(jq -r '.body' < $GITHUB_EVENT_PATH | grep -E '^\s*- \[x\].*')
          if echo "$completed" | grep -qE '^\s*- \[ \].*'; then
            echo "Checklist items not completed"
            exit 1
          else
            echo "Checklist items completed"
          fi

      - name: Add labels
        if: success()
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
            
            if (pullRequest.labels.some(label => label.name === 'Checklist Items Incomplete')) {
              await github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                name: 'Checklist Items Incomplete'
              })
            }
            
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['Checklist Items Complete']
            })
